spring:
  application:
    name: springcloud-eureka

server:
  port: 8000

eureka:
  instance: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance}:${server.port}/eureka/
